### ISSUE TITLE
After updating to 1.0.0, the sensor fails to update if local_currency is specified

### ISSUE THREAD

**Issue by shadowpanther** [ThomasPrior/EthermineInfo#11]
**Describe the issue**
The sensor fails to update if the `currency_name` parameter is specified

**To Reproduce**
1. Configure the sensor like in the example
2. Restart HA to apply the new config
3. Observe the sensor not updating and this in the log:
```
2021-05-21 18:53:48 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.ethermineinfo_metamask fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 316, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 524, in async_device_update
    raise exc
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 280, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/ethermineinfo/sensor.py", line 212, in _update
    self._single_coin_in_local_currency = r4.json()['ethereum'][self.local_currency]
KeyError: 'USD'
```
4. Removing the parameter and restarting HA fixes the sensor

**Expected behaviour**
Sensor updates correctly, no exceptions in the log

**Configuration**
```
  - platform: ethermineinfo
    miner_address: "0x..."
    currency_name: USD
    name_override: "Metamask"
```

**Environment (please complete the following information):**
## System Health

version | core-2021.5.5
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.0-62-generic
arch | x86_64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4642
Installed Version | 1.12.3
Stage | running
Available Repositories | 825
Installed Repositories | 26

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 10
views | 6
mode | storage

</details>

**Additional context**

**Comment by ThomasPrior** [comment]
I was able to replicate that. Could you try changing the currency_name in your config to lower case and try again?

**Comment by shadowpanther** [comment]
Yes, the lowercase `usd` fixed the issue.

**Comment by ThomasPrior** [comment]
Many thanks for logging this issue, I've pushed a new release that includes the fix.
