### ISSUE TITLE
Entity sensor.ethermineinfo_eth (<class 'custom_components.ethermineinfo.sensor.EthermineInfoSensor'>) implements device_state_attributes. Please report it to the custom component author.

### ISSUE THREAD

**Issue by sunshine-hass** [ThomasPrior/EthermineInfo#16]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
First occurred: 09:46:41 (1 occurrences)
Last logged: 09:46:41

Entity sensor.ethermineinfo_eth (<class 'custom_components.ethermineinfo.sensor.EthermineInfoSensor'>) implements device_state_attributes. Please report it to the custom component author.

System Health

version: core-2021.12.6
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.83
arch: x86_64
timezone: Asia/Shanghai

GitHub API: ok
Github API Calls Remaining: 4885
Installed Version: 1.18.0
Stage: running
Available Repositories: 932
Installed Repositories: 15

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: ok
can_reach_cloud: ok

host_os: Home Assistant OS 7.0
update_channel: stable
supervisor_version: supervisor-2021.12.2
docker_version: 20.10.9
disk_total: 30.8 GB
disk_used: 18.1 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: ok
installed_addons: File editor (5.3.3), Mosquitto broker (6.0.1), Terminal & SSH (9.2.2), RPC Shutdown (2.2), Node-RED (9.2.1), Samba share (9.5.1), ESPHome (1.20.3), Duck DNS (1.14.0), InfluxDB (4.3.0), Nginx Proxy Manager (0.11.0)

dashboards: 1
resources: 6
views: 3
mode: storage

**Comment by ThomasPrior** [comment]
Thanks for this - I've just pushed out https://github.com/ThomasPrior/EthermineInfo/tree/v1.0.12 which should solve this.
