### ISSUE TITLE
[ISSUE] It do not work again after 12-30-2021

### ISSUE THREAD

**Issue by NapalmCandy** [ThomasPrior/EthermineInfo#17]
**Describe the issue**
All sensor of the integration are in "unknown" state

This is what the log says:

`Este error se originó a partir de una integración personalizada.

Logger: homeassistant.helpers.entity
Source: custom_components/ethermineinfo/sensor.py:190 
Integration: ethermineinfo (documentation, issues) 
First occurred: 23:38:00 (7 occurrences) 
Last logged: 23:41:26

Update for sensor.ethermineinfo_ethermine_alsaje fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 195, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/ethermineinfo/sensor.py", line 190, in _update
    self._state = r.json()['data']['currentStatistics']['activeWorkers']
KeyError: 'activeWorkers'`

This is in my sensors.yaml 
`  - platform: ethermineinfo
    miner_address: "0xa2fF046A6346f686Ba8Cf77C28706F4319600613"
    currency_name: EUR
    name_override: "Ethermine Alsaje"`

**Comment by NapalmCandy** [comment]
still don't work...

**Comment by ThomasPrior** [comment]
Yes, that will happen until I have some time to work on it. Comments like this aren't terribly helpful.

The sensor will however start working again as soon as you have an active worker.

**Comment by NapalmCandy** [comment]
Sorry if you feel my comment angry. Not my intention. English it is not my primary language.

I do not have any inactive worker, all are active, I tried with another wallet, and has the same problem

**Comment by ThomasPrior** [comment]
This should be fixed in https://github.com/ThomasPrior/EthermineInfo/releases/tag/v1.0.12

**Comment by NapalmCandy** [comment]
The last release as I read solves the problem with inactive workers. But as I said in last message I have no inactive workers.

So the integration still doesn't work. Can I provide more info to find where it is the problem?

Greetings

**Comment by ThomasPrior** [comment]
I can't help you if you don't provide logs.

I have tested with inactive workers and active ones from the list of top
miners on Ethermine.org.

As far as I can see this component is working for both scenarios.

**Comment by ThomasPrior** [comment]
I've just put in the same address as in your initial report into my own config and it works on both my dev instance and my prod instance.

The component works without issue for this address.

```
  - platform: ethermineinfo
    miner_address: "0xa2fF046A6346f686Ba8Cf77C28706F4319600613"
    currency_name: eur
```

![image](https://user-images.githubusercontent.com/34111848/152642423-4f8f8127-d8ff-4c17-b9bb-92b12c3790ba.png)

**Comment by NapalmCandy** [comment]
Sorry, by bad. I changed accidentaly the name of the sensor, and do not work any template because it.

Thanks for trying and your time, and sorry again :)

**Comment by ThomasPrior** [comment]
Don't worry, we've all been there! I'm happy you have it working and there's nothing bigger going on :)
